import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Poppins } from "next/font/google";
import "./globals.css";
import TopNavbar from "./components/navbar/topnavbar/TopNavbar";
import BottomNavbar from "./components/navbar/bottomnavbar/BottomNavbar";

// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap", // Optional: Improves performance
});
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${montserrat.variable}
          ${poppins.variable}
          antialiased
        `}
      >
        <div className=" w-full md:mx-0 lg:mx-auto">
          <div className="lg:mx-40 relative">
            <TopNavbar />
            <hr className="text-gray-300" />
            <BottomNavbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
